// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/git-config/git-config.d.ts
declare module "git-config" {
    export function sync(gitFile?: string): Object; // Synchronous version.
}