// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/7de6c3dd94feaeb21f20054b9f30d5dabc5efabd/through/through.d.ts
// Type definitions for through
// Project: https://github.com/dominictarr/through
// Definitions by: Andrew Gaspar <https://github.com/AndrewGaspar/>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped


declare module "through" {
    import stream = require("stream");

    function through(write?: (data: any) => void,
        end?: () => void,
        opts?: {
            autoDestroy: boolean;
        }): through.ThroughStream;

    namespace through {
        export interface ThroughStream extends stream.Transform {
            autoDestroy: boolean;
        }
    }

    export = through;
}